# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
codecov: true
os:
  - linux
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly

matrix:
 allow_failures:
   - julia: nightly

before_script:
    - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/JuliaAlgebra/MultivariatePolynomials.jl", rev="bl/mutable_arithmetics"))'

notifications:
  email: false
branches:
  only: master
