# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.7
  - 1.0
  - nightly

matrix:
 allow_failures:
   - 1.0
   - julia: nightly

notifications:
  email: false
branches:
  only: master
#
# before_install:
#   - julia -e 'Pkg.init()'
#   - julia -e 'Pkg.clone("https://github.com/JuliaAlgebra/MultivariatePolynomials.jl")'

after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("TypedPolynomials")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
