(p::Polynomial)(s::Substitution...) = subs(p, s)
(p::Polynomial)(s::MultiSubstitution) = subs(p, s)
(p::Term)(s::Substitution...) = subs(p, s)
(p::Term)(s::MultiSubstitution) = subs(p, s)
(p::Monomial)(s::Substitution...) = subs(p, s)
(p::Monomial)(s::MultiSubstitution) = subs(p, s)
(p::Variable)(s::Substitution...) = subs(p, s...)
(p::Variable)(s::MultiSubstitution) = subs(p, pairzip(s)...)
